### ISSUE TITLE
Is there a reason for initModuleDataSources method not exists in ActionServlet?

### ISSUE THREAD

**Issue by JanioSamuel** [weblegacy/struts1#15]
Hello, 
I'm facing a problem using this version of struts 1 because in my project we use a protected method "initModuleDataSources" from ActionServlet.
I would like to know if there is any reason to this method being removed from this version. And if exists a reason, what method I could use to adapt my code?

Thank you.

**Comment by ste-gr** [comment]
Hi,
I did some researches and found, that the `data-sources` were removed with version 1.3.
Since this version is/should be an successor of Struts1 1.3.10, the `initModuleDataSources` is no longer available.

I have found the following resources that may be of interest to you:
* [Notes on upgrading from 1.2 to 1.3](https://web.archive.org/web/20150923041220/http://wiki.apache.org/struts/StrutsUpgradeNotes12to13)
* [StackOverflow - Configure Data Source - Struts 1.3.8](https://stackoverflow.com/questions/10161710/configure-data-source-struts-1-3-8)]

Greetings
Stefan
